name: gh-pages
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: mv .obsidian _.obsidian

      - uses: actions/upload-artifact@v2
        with:
          name: gh-pages
          path: .
          retention-days: 30

  push:
    needs: build
    runs-on: ubuntu-latest
    env:
      FLEEK_TOKEN: ${{ secrets.FLEEK_TOKEN }}
      FLEEK_PROJECT_ID: ${{ secrets.FLEEK_PROJECT_ID }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v2
        with:
          name: gh-pages
          path: gh-pages

      - id: hash
        run: echo "::set-output name=hash::$(git rev-parse HEAD)"

      - uses: peaceiris/actions-gh-pages@v3
        if: ${{ steps.hash.outputs.hash != github.event.before }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: gh-pages
          publish_branch: gh-pages

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm i -g @fleekxyz/cli

      - if: ${{ steps.hash.outputs.hash != github.event.before }}
        run: cd gh-pages && pwsh publish.ps1
