name: gh-pages
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    timeout-minutes: 240
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4

      - uses: moonrepo/setup-rust@v1
        with:
          channel: 'nightly-2024-10-07'
          components: 'clippy,rust-src,rustfmt'
          targets: 'wasm32-unknown-unknown'

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.200'

      - uses: actions/setup-node@v4
        with:
          node-version: 21

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - uses: actions/setup-go@v5

      - uses: awalsh128/cache-apt-pkgs-action@master
        with:
          packages: texlive-xetex texlive-full pandoc fonts-nanum-coding
          version: 1.0

      - run: pwsh scripts/workflow.ps1

      - uses: actions/upload-artifact@v4
        with:
          name: gh-pages
          path: dist
          retention-days: 30

  push:
    needs: build
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      FLEEK_TOKEN: ${{ secrets.FLEEK_TOKEN }}
      FLEEK_PROJECT_ID: ${{ secrets.FLEEK_PROJECT_ID }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: gh-pages
          path: gh-pages

      - id: hash
        run: echo "::set-output name=hash::$(git rev-parse HEAD)"

      - uses: peaceiris/actions-gh-pages@v4
        if: ${{ steps.hash.outputs.hash != github.event.before }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: gh-pages

      - uses: actions/setup-node@v4
        with:
          node-version: 21

      - if: ${{ steps.hash.outputs.hash != github.event.before }}
        run: pwsh gh-pages/scripts/publish-fleek.ps1
